on: push
jobs:
  login:
      runs-on: self-hosed
      steps:
         - name: login-docker
           uses: docker/login-action@v4
           with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}